--- #YAML:1.0
name:               CDDB_get
version:            2.28.1
abstract:           This module/script gets the CDDB info for an audio cd.
author:
    - Armin Obersteiner <armin at xos dot net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
